# Generated by Django 3.1.6 on 2021-04-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210331_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/demo.png', null=True, upload_to=''),
        ),
    ]
